SELECT NAME
FROM MOVIESTAR
WHERE GENDER='F' AND MOVIESTAR.NAME IN(SELECT NAME FROM MOVIEEXEC WHERE NETWORTH> 10000)

SELECT NAME
FROM MOVIESTAR
WHERE  MOVIESTAR.NAME NOT IN(SELECT NAME FROM MOVIEEXEC )


SELECT TITLE
FROM MOVIE 
WHERE LENGTH > ALL( SELECT LENGTH FROM MOVIE WHERE TITLE='Star Wars')

SELECT MOVIE.TITLE, MOVIEEXEC.NAME
FROM MOVIE, MOVIEEXEC
WHERE MOVIE.PRODUCERC#=MOVIEEXEC.CERT# AND MOVIEEXEC.CERT# IN(
SELECT CERT#
FROM MOVIEEXEC
WHERE NETWORTH>(SELECT NETWORTH FROM MOVIEEXEC WHERE NAME='Merv Griffin'))

