SELECT TITLE,NAME
FROM MOVIE,MOVIEEXEC
WHERE PRODUCERC#=CERT# AND CERT# IN(
SELECT CERT#
FROM MOVIE
JOIN MOVIEEXEC ON CERT#=PRODUCERC#
WHERE TITLE='Star Wars')


SELECT DISTINCT NAME
FROM MOVIEEXEC
JOIN MOVIE ON PRODUCERC#=CERT#
WHERE TITLE IN(
SELECT MOVIETITLE
FROM STARSIN
WHERE STARNAME='Harrison Ford')


SELECT DISTINCT studioname,starname
FROM MOVIE 
JOIN STARSIN ON MOVIETITLE=TITLE AND year=MOVIEYEAR
ORDER BY STUDIONAME,STARNAME

SELECT title, STARNAME
FROM MOVIE
JOIN STARSIN ON MOVIETITLE=title AND MOVIEYEAR=year
WHERE PRODUCERC# IN(
SELECT CERT#
FROM MOVIEEXEC
WHERE NETWORTH >= ALL(SELECT NETWORTH FROM MOVIEEXEC))

SELECT name,MOVIETITLE as movietitle
FROM MOVIESTAR
LEFT JOIN STARSIN ON name=STARNAME
WHERE MOVIETITLE IS NULL


