

 SELECT NAME,COUNTRY
 FROM SHIPS
 LEFT JOIN OUTCOMES ON SHIPS.name=outcomes.SHIP 
 INNER JOIN CLASSES ON Classes.class=ships.class
 WHERE OUTCOMES.ship IS NULL
 ORDER BY COUNTRY

 SELECT ships.name
 FROM SHIPS
 INNER JOIN CLASSES ON SHIPS.class=classes.class 
 WHERE LAUNCHED=1916 AND numguns>7
 

