SELECT title,year,length
FROM Movie
WHERE (length > 120 OR length IS NULL) AND year<2000


SELECT name,gender
FROM MOVIESTAR
WHERE name LIKE 'J%' AND DATEPART(yy,BIRTHDATE)>1948


SELECT STUDIO.name, COUNT(DISTINCT STARNAME)
FROM MOVIE
JOIN STUDIO ON STUDIO.NAME=MOVIE.STUDIONAME
JOIN STARSIN ON STARSIN.MOVIETITLE=MOVIE.title
GROUP BY STUDIO.name


SELECT STARSIN.STARNAME, COUNT(DISTINCT title)
FROM STARSIN
JOIN MOVIE ON STARSIN.MOVIETITLE=MOVIE.TITLE
GROUP BY STARNAME

SELECT t1.studioName,t1.year, MOVIE.title
FROM
(SELECT STUDIO.NAME as studioName,MAX(year) as year
FROM MOVIE
JOIN STUDIO ON STUDIO.NAME=MOVIE.STUDIONAME
GROUP BY STUDIO.NAME ) t1
INNER JOIN MOVIE ON t1.studioName=MOVIE.STUDIONAME AND MOVIE.YEAR=t1.year

SELECT TOP 1 NAME
FROM MOVIESTAR
WHERE GENDER='M'
ORDER BY BIRTHDATE DESC






